# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#trigger:
#- cypress/setup

steps:

- script: npm ci
  displayName: 'Install NPM dependencies'

- script: node --version
  displayName: 'check node version'

- script: |
    npm install
  displayName: 'npm install'

- script: npm cache clean --force 
  displayName: 'Clear cache'

- script: npx cypress verify
  displayName: 'Cypress verify'

- script: |
    cd $(Build.SourcesDirectory)
    
     npx cypress run --spec "./cypress/e2e/features/*.feature" 

  displayName: 'Run Cypress tests'
  env:
    # avoid warnings about terminal
    TERM: xterm

    

- task: CmdLine@2
  displayName: Check Job outcome
  inputs:
   script: |
      echo 'The job status is ' +  $(Agent.JobStatus)

